import type { Metadata } from 'next'
import './globals.css'
import StyledComponentsRegistry from "@/style/styledComponentRegistry";
import CustomProvider from "@/lib/redux/ReduxProvider";



export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <CustomProvider>
          <StyledComponentsRegistry>
              {children}
          </StyledComponentsRegistry>
        </CustomProvider>
      </body>
    </html>
  )
}
